### ISSUE TITLE
Benchmarking test case result can't be gotten

### ISSUE THREAD

**Issue by shuiqing05** [istio/tools#125]
Hi,
    From README, some CSV file will be generated after benchmarking case finished. However, I can't find them. From the code, the method "output_csv" even doesn't used. Is this a bug for this case?
    Thanks!

**Comment by howardjohn** [comment]
Did you pass the `--csv` flag? From the readme, you need to pass it with all columns you want. For example:

```
python ./runner/fortio.py FORTIO_CLIENT_URL PROMETHEUS_URL --csv StartTime,ActualDuration,Labels,NumThreads,ActualQPS,p50,p90,p99,cpu_mili_avg_telemetry_mixer,cpu_mili_max_telemetry_mixer,mem_MB_max_telemetry_mixer,cpu_mili_avg_fortioserver_deployment_proxy,cpu_mili_max_fortioserver_deployment_proxy,mem_MB_max_fortioserver_deployment_proxy,cpu_mili_avg_ingressgateway_proxy,cpu_mili_max_ingressgateway_proxy,mem_MB_max_ingressgateway_proxy
```

Then it will output something like "Saved results to /tmp/asjdoidwq" which is the CSV

Looks like you are write about output_csv not being used, but we do use write_csv, so probably just some old dead code. I think @mandarjog had some changes he had made to the script to improve this part but haven't been merged yet

**Comment by shuiqing05** [comment]
> Did you pass the `--csv` flag? From the readme, you need to pass it with all columns you want. For example:
> 
> ```
> python ./runner/fortio.py FORTIO_CLIENT_URL PROMETHEUS_URL --csv StartTime,ActualDuration,Labels,NumThreads,ActualQPS,p50,p90,p99,cpu_mili_avg_telemetry_mixer,cpu_mili_max_telemetry_mixer,mem_MB_max_telemetry_mixer,cpu_mili_avg_fortioserver_deployment_proxy,cpu_mili_max_fortioserver_deployment_proxy,mem_MB_max_fortioserver_deployment_proxy,cpu_mili_avg_ingressgateway_proxy,cpu_mili_max_ingressgateway_proxy,mem_MB_max_ingressgateway_proxy
> ```
> 
> Then it will output something like "Saved results to /tmp/asjdoidwq" which is the CSV
> 
> Looks like you are write about output_csv not being used, but we do use write_csv, so probably just some old dead code. I think @mandarjog had some changes he had made to the script to improve this part but haven't been merged yet

Yes, I added the "--csv" in the command. And from the path you gave, I found the csv file.
